export const PATH = {
  MAIN: '/',
  HOME: '/home',
  AUTH: {
    LOGIN: '/auth/login',
    SIGNUP: '/auth/signup',
    VERIFICATION_LINK_EXPIRED: '/auth/verification-link-expired',
    RECOVERY_LINK_EXPIRED: '/auth/recovery-link-expired',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RECOVERY: '/auth/recovery',
    PRIVACY_POLICY: '/auth/privacy-policy',
    REGISTRATION_CONFIRMATION: '/auth/registration-confirmation',
    TERMS_OF_SERVICE: '/auth/terms-of-service',
    UPDATE_TOKENS: '/auth/update-tokens',
    ME: '/auth/me',
  },
  GITHUB: '/github',
  PROFILE: {
    PROFILE: '/profile',
    SETTINGS: '/profile/settings',
  },
  CREATE: '/create',
  FAVORITES: '/favorites',
  MESSENGER: '/messenger',
  STATISTICS: '/statistics',
  SEARCH: '/search',
  PUBLIC_PAGE: '/public-page',
}
